# Example OTAP Collector configuration with Geneva exporter
#
# This configuration shows how to send logs from OTLP receiver to Microsoft Geneva backend
# using the Geneva exporter with OTAP log encoding.

receivers:
  otlp:
    type: "urn:otel:otlp:receiver"
    config:
      endpoint: "0.0.0.0:4317"
      # Optional: configure compression
      # compression_method: gzip

exporters:
  geneva:
    type: "urn:otel:geneva:exporter"
    config:
      # Geneva backend endpoint
      endpoint: "https://your-geneva-endpoint.monitoring.core.windows.net"
      
      # Environment and account information
      environment: "production"
      account: "your-account-name"
      namespace: "your-namespace"
      region: "eastus"
      
      # Tenant and role information
      tenant: "your-tenant"
      role_name: "otel-collector"
      role_instance: "collector-instance-1"
      
      # Geneva config version (default: 1)
      config_major_version: 1
      
      # Authentication - choose one method:
      
      # Option 1: Certificate-based authentication
      auth:
        type: "certificate"
        cert_path: "/path/to/your/cert.pem"
        key_path: "/path/to/your/key.pem"
      
      # Option 2: System-assigned managed identity (Azure)
      # auth:
      #   type: "systemmanaged_identity"
      #   msi_resource: "https://monitoring.azure.com/"
      
      # Option 3: User-assigned managed identity (Azure)
      # auth:
      #   type: "usermanaged_identity"
      #   client_id: "your-client-id"
      #   msi_resource: "https://monitoring.azure.com/"
      
      # Option 4: Workload identity (Kubernetes)
      # auth:
      #   type: "workloadidentity"
      #   client_id: "your-client-id"
      #   tenant_id: "your-tenant-id"
      #   msi_resource: "https://monitoring.azure.com/"
      
      # Performance tuning (optional)
      max_concurrent_uploads: 4    # Number of concurrent upload connections
      max_buffer_size: 1000         # Buffer size before forcing flush

pipelines:
  logs/production:
    receivers:
      - otlp
    processors: []
    exporters:
      - geneva

# Additional pipeline examples:

# Example: Multiple pipelines with different Geneva accounts
# pipelines:
#   logs/account1:
#     receivers: [otlp]
#     processors: []
#     exporters: [geneva_account1]
#   
#   logs/account2:
#     receivers: [otlp]
#     processors: []
#     exporters: [geneva_account2]

# Example: With processors for filtering/transformation
# pipelines:
#   logs/filtered:
#     receivers: [otlp]
#     processors:
#       - attributes  # Add/modify attributes
#       - batch       # Batch logs before export
#     exporters: [geneva]
