settings:
  default_pipeline_ctrl_msg_channel_size: 100
  default_node_ctrl_msg_channel_size: 100
  default_pdata_channel_size: 100

nodes:
  receiver:
    kind: receiver
    plugin_urn: "urn:otel:otlp:receiver"
    out_ports:
      out_port:
        destinations:
          - exporter
        dispatch_strategy: round_robin
    config:
      listening_addr: "0.0.0.0:4317"
  exporter:
    kind: exporter
    plugin_urn: "urn:otel:geneva:exporter"
    config:
      endpoint: "https://ingestion.monitor.azure.com"
      environment: "prod"
      account: "your-account"
      namespace: "your-namespace"
      region: "eastus"
      config_major_version: 1
      tenant: "your-tenant"
      role_name: "collector-role"
      role_instance: "collector-instance"
      auth_method: "managed_identity"
      identity_resource: "https://monitor.azure.com/"
      managed_identity_client_id: null
      cert_path: null
      cert_password: null
      max_concurrent_uploads: 8
      upload_queue_size: 512
      batch_retry:
        enabled: true
        max_retries: 5
        initial_interval: "250ms"
        max_interval: "10s"
        multiplier: 2.0
