// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProfilesDictionary {
    #[prost(message, repeated, tag = "1")]
    pub mapping_table: ::prost::alloc::vec::Vec<Mapping>,
    #[prost(message, repeated, tag = "2")]
    pub location_table: ::prost::alloc::vec::Vec<Location>,
    #[prost(message, repeated, tag = "3")]
    pub function_table: ::prost::alloc::vec::Vec<Function>,
    #[prost(message, repeated, tag = "4")]
    pub link_table: ::prost::alloc::vec::Vec<Link>,
    #[prost(string, repeated, tag = "5")]
    pub string_table: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "6")]
    pub attribute_table: ::prost::alloc::vec::Vec<KeyValueAndUnit>,
    #[prost(message, repeated, tag = "7")]
    pub stack_table: ::prost::alloc::vec::Vec<Stack>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProfilesData {
    #[prost(message, repeated, tag = "1")]
    pub resource_profiles: ::prost::alloc::vec::Vec<ResourceProfiles>,
    #[prost(message, optional, tag = "2")]
    pub dictionary: ::core::option::Option<ProfilesDictionary>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ResourceProfiles {
    #[prost(message, optional, tag = "1")]
    pub resource: ::core::option::Option<super::super::resource::v1::Resource>,
    #[prost(message, repeated, tag = "2")]
    pub scope_profiles: ::prost::alloc::vec::Vec<ScopeProfiles>,
    #[prost(string, tag = "3")]
    pub schema_url: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ScopeProfiles {
    #[prost(message, optional, tag = "1")]
    pub scope: ::core::option::Option<super::super::common::v1::InstrumentationScope>,
    #[prost(message, repeated, tag = "2")]
    pub profiles: ::prost::alloc::vec::Vec<Profile>,
    #[prost(string, tag = "3")]
    pub schema_url: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Profile {
    #[prost(message, optional, tag = "1")]
    pub sample_type: ::core::option::Option<ValueType>,
    #[prost(message, repeated, tag = "2")]
    pub samples: ::prost::alloc::vec::Vec<Sample>,
    #[prost(fixed64, tag = "3")]
    pub time_unix_nano: u64,
    #[prost(uint64, tag = "4")]
    pub duration_nano: u64,
    #[prost(message, optional, tag = "5")]
    pub period_type: ::core::option::Option<ValueType>,
    #[prost(int64, tag = "6")]
    pub period: i64,
    #[prost(bytes = "vec", tag = "7")]
    pub profile_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "8")]
    pub dropped_attributes_count: u32,
    #[prost(string, tag = "9")]
    pub original_payload_format: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "10")]
    pub original_payload: ::prost::alloc::vec::Vec<u8>,
    #[prost(int32, repeated, tag = "11")]
    pub attribute_indices: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Link {
    #[prost(bytes = "vec", tag = "1")]
    pub trace_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub span_id: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ValueType {
    #[prost(int32, tag = "1")]
    pub type_strindex: i32,
    #[prost(int32, tag = "2")]
    pub unit_strindex: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Sample {
    #[prost(int32, tag = "1")]
    pub stack_index: i32,
    #[prost(int32, repeated, tag = "2")]
    pub attribute_indices: ::prost::alloc::vec::Vec<i32>,
    #[prost(int32, tag = "3")]
    pub link_index: i32,
    #[prost(int64, repeated, tag = "4")]
    pub values: ::prost::alloc::vec::Vec<i64>,
    #[prost(fixed64, repeated, tag = "5")]
    pub timestamps_unix_nano: ::prost::alloc::vec::Vec<u64>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Mapping {
    #[prost(uint64, tag = "1")]
    pub memory_start: u64,
    #[prost(uint64, tag = "2")]
    pub memory_limit: u64,
    #[prost(uint64, tag = "3")]
    pub file_offset: u64,
    #[prost(int32, tag = "4")]
    pub filename_strindex: i32,
    #[prost(int32, repeated, tag = "5")]
    pub attribute_indices: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Stack {
    #[prost(int32, repeated, tag = "1")]
    pub location_indices: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Location {
    #[prost(int32, tag = "1")]
    pub mapping_index: i32,
    #[prost(uint64, tag = "2")]
    pub address: u64,
    #[prost(message, repeated, tag = "3")]
    pub lines: ::prost::alloc::vec::Vec<Line>,
    #[prost(int32, repeated, tag = "4")]
    pub attribute_indices: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Line {
    #[prost(int32, tag = "1")]
    pub function_index: i32,
    #[prost(int64, tag = "2")]
    pub line: i64,
    #[prost(int64, tag = "3")]
    pub column: i64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Function {
    #[prost(int32, tag = "1")]
    pub name_strindex: i32,
    #[prost(int32, tag = "2")]
    pub system_name_strindex: i32,
    #[prost(int32, tag = "3")]
    pub filename_strindex: i32,
    #[prost(int64, tag = "4")]
    pub start_line: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KeyValueAndUnit {
    #[prost(int32, tag = "1")]
    pub key_strindex: i32,
    #[prost(message, optional, tag = "2")]
    pub value: ::core::option::Option<super::super::common::v1::AnyValue>,
    #[prost(int32, tag = "3")]
    pub unit_strindex: i32,
}
